import { Toaster } from "react-hot-toast";
import { DarkModeProvider } from "../providers/darkMode";
import "./globals.css";


export const metadata = {
  title: "Prontu e Ponto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body>
          <DarkModeProvider>
            <Toaster toastOptions={{
            className: 'colorsAlerts'
            }}/>
            {children}
          </DarkModeProvider>
      </body>
    </html>
  );
}
